### PR TITLE
Lower the amount of candidates used when searching for the closestAre…

### PR DESCRIPTION
**Pull request by jemster**
…aToPoint

### CODE REVIEW

**Review by ankovi — DISMISSED** [review]
Changing the limit on the spatial query should not be done. This is because  depending on where the point is located we are not sure that the subquery results will retrieve the closest areas.

**Comment by jemster** [comment]
To test the effects of lowering the limit in the nearest area query in spatial I created 4000 random points spread out all over the globe. Of those 4000 roughly 70% are in water. I then ran those points against the query, printed and copied the result to a text file. I then used Beyond Compare to compare the results.

First conclusion is that there is a bug in ST_Distance so that certain areas always return 0 meters distance. To get an actually correct result, _ST_DistanceUnCached is needed. Hopefully this bug is fixed in the next release (2.5.2) of postGIS.

I tested limit values of 50 (current value), 20, 10 and 5. The result is for limit values down to 10 RFMO, FAO, and EEZ areas remain the same as for 50 while PORTAREA, STATRECT and GFCM differ and they differ more the farther away the comparison point are. I then asked Mats Börje, the product owner for the swe team, about the importance of knowing how near a position is to those areas. His response was that, for those areas, he only cares if ships are IN the areas, not if they are near them. He also said that he wanted a fast system since “We have enough slow systems already”. 

It should also be noted that for port areas, the erroneous result start to occur way beyond the 22224 meter limit currently in place for determining the nearest port. 

As for speed, the test query took 16 minutes for limit 50 unchached while limit 10 took 10 minutes, a rather substantial performance increase.

**Comment by jemster** [comment]
test me

**Comment by jemster** [comment]
@hfpmartins

**Review by hfpmartins — APPROVED** [review]
Jonas has made some tests and found out a bug on PostGIS. With his findings we can now confidently lower the limit of searching areas.

**Pull request merged**
